- rework init-scripts ...
* small format-fixes
* use aliases from /etc/init.d/gobals
* allow stop w/o flagfile
* add own init-scripts for tuxcald and tuxmaild

diff --git a/archive-imagefiles/scripts/samba3.init b/archive-imagefiles/scripts/samba3.init
--- a/archive-imagefiles/scripts/samba3.init
+++ b/archive-imagefiles/scripts/samba3.init
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+. /etc/init.d/globals
+
 SMB_CONF=/etc/samba/smb.conf
 
 case "$1" in
@@ -21,23 +23,19 @@ case "$1" in
 				fi
 			done
 		fi
-		;;
+	;;
 	stop)
-		if [ -e /var/etc/.samba ]; then
-			for i in nmbd smbd; do
-				printf "stopping $i ..."
-				if pidof $i > /dev/null; then
-					read pid < /var/run/${i}.pid
-					kill $pid && echo "done" || echo "failed!?"
-				else
-					echo "not running"
-				fi
-			done
-		fi
-		;;
+		for i in nmbd smbd; do
+			printf "stopping $i ..."
+			if pidof $i > /dev/null; then
+				read pid < /var/run/${i}.pid
+				kill $pid && echo "done" || echo "failed!?"
+			else
+				echo "not running"
+			fi
+		done
+	;;
 	*)
-		echo "usage: $0 <start|stop>"
-		;;
+		echo "[$BASENAME] Usage: $0 {start|stop}"
+	;;
 esac
-
-exit 0
